apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Securesign is the Schema for the securesigns API
      displayName: Securesign
      kind: Securesign
      name: securesigns.rhtas.redhat.com
      version: v1alpha1
  description: Red Hat Trusted Artifact Signer
  displayName: Red Hat Trusted Artifact Signer
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - Secure Supply Chain
  links:
  - name: Operator
    url: https://operator.domain
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.0
