apiVersion: rhtas.redhat.com/v1alpha1
kind: Securesign
metadata:
  labels:
    app.kubernetes.io/name: securesign
    app.kubernetes.io/instance: securesign-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: securesign-sample
spec:
  rekorPrivateKey: | #notsecret
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEICnmFR7rXoJ3QujB9SzrKbVtXCikPXtEb2rs8EGgzYrSoAoGCCqGSM49
    AwEHoUQDQgAEnItR5lDp+1fPho5A2npEr9CygZ3lVGXB6jc0MAS/bez9PxUlPacS
    XrlASWbaMaLIoporoKnYhoGHd1oiiVq1lg==
    -----END EC PRIVATE KEY-----
