name: Validate SecureSign
on: 
  push:
    branches: ["main", "release*"]
    tags: ["*"]
  pull_request:
    branches: ["main", "release*"]

env:
  GO_VERSION: 1.19
  OPERATOR_IMAGE: quay.io/rcook/securesign-operator:latest
  CONTROLLER_IMAGE: quay.io/rcook/securesign-controller:latest


jobs:
  build-operator:
    name: Build-operator
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Test
        run: make test

      - name: Build operator container
        run: make docker-build CONTROLLER_IMAGE=${CONTROLLER_IMAGE}

      - name: debug
        run: docker images

      - name: Export container image as a tar file
        run: docker save ${CONTROLLER_IMAGE} -o controller.tar

      - name: archive controller container
        uses: actions/upload-artifact@v2
        with:
          name: controller
          path: controller.tar