name: Validate SecureSign
on: 
  push:
    branches: ["main", "release*"]
    tags: ["*"]
  pull_request:
    branches: ["main", "release*"]

env:
  GO_VERSION: 1.19
  OPERATOR_IMAGE: quay.io/rcook/securesign-operator:latest


jobs:
  build-operator:
    name: Build-operator
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Test
        run: make test

      - name: Build operator container
        run: make docker-build OPERATOR_IMAGE=${OPERATOR_IMAGE}

      - name: Export container image
        run: docker save -o /tmp/operator.tar ${OPERATOR_IMAGE}

      - name: Save container as artifact
        uses: actions/upload-artifact@v1
        with:
          name: signer-operator
          path: /tmp/operator.tar
